# Generated by Django 5.2.3 on 2025-07-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_kpay_qr_url_organization_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="kpay_qr_image",
            field=models.ImageField(blank=True, null=True, upload_to="kpay_qr_images"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="kpay_qr_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
