# Generated by Django 5.2.3 on 2025-07-09 16:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receiver_object_id", models.UUIDField()),
                ("source_object_id", models.UUIDField()),
                ("title", models.CharField(max_length=255)),
                ("highlight", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("failure", "Failure"),
                            ("success", "Success"),
                            ("pending", "Pending"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("debug", "Debug"),
                            ("critical", "Critical"),
                            ("fatal", "Fatal"),
                            ("unknown", "Unknown"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "receiver_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_received",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_sent",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
